add

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,5 +1,14 @@
 #!/usr/bin/env bash
 
+versionUrl=https://api.github.com/repos/JDongKhan/flutter_yaml_plus/releases/latest
+downloadUrl=https://github.com/JDongKhan/flutter_yaml_plus/archive/refs/tags
+# Setup installation directory and symlink
+BIN_NAME="pub+"
+BIN_DIR="$HOME/.$BIN_NAME"
+BIN_DIR_BIN="$BIN_DIR/bin"
+SYMLINK_TARGET="/usr/local/bin/$BIN_NAME"
+projectName="flutter_yaml_plus"
+
 # Function to log messages with date and time
 log_message() {
     echo -e "$1"
@@ -24,72 +33,75 @@ if ! command -v curl &> /dev/null; then
     error "curl is required but not installed."
 fi
 
-# Get installed FVM version if exists
+# Get installed BIN version if exists
 INSTALLED_VERSION=""
-if command -v pub+ &> /dev/null; then
-    INSTALLED_VERSION=$(fvm --version 2>&1) || error "Failed to fetch installed FVM version."
+if command -v $BIN_NAME &> /dev/null; then
+    INSTALLED_VERSION=$($BIN_NAME --version 2>&1) || error "Failed to fetch installed $BIN_NAME version."
 fi
 
-# Define the URL of the FVM binary
+log_message "Local version $INSTALLED_VERSION."
+
+# Define the URL of the BIN binary
 if [ -z "$1" ]; then
-  FVM_VERSION=$(curl -s https://api.github.com/repos/leoafarias/fvm/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
-  if [ -z "$FVM_VERSION" ]; then
-      error "Failed to fetch latest FVM version."
+  BIN_VERSION=$(curl -s $versionUrl | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
+  if [ -z "$BIN_VERSION" ]; then
+      error "Failed to fetch latest $BIN_NAME version."
   fi
 else
-  FVM_VERSION="$1"
+  BIN_VERSION="$1"
 fi
 
-log_message "Installing FVM version $FVM_VERSION."
+log_message "Installing $BIN_NAME version $BIN_VERSION."
 
-# Setup installation directory and symlink
-FVM_DIR="$HOME/.fvm_flutter"
-FMV_DIR_BIN="$FVM_DIR/bin"
-SYMLINK_TARGET="/usr/local/bin/fvm"
+# Create BIN directory if it doesn't exist
+mkdir -p "$BIN_DIR" || error "Failed to create BIN directory: $BIN_DIR."
 
-
-# Create FVM directory if it doesn't exist
-mkdir -p "$FVM_DIR" || error "Failed to create FVM directory: $FVM_DIR."
-
-# Check if FVM_DIR exists, and if it does delete it
-if [ -d "$FMV_DIR_BIN" ]; then
-    log_message "FVM bin directory already exists. Removing it."
-    if ! rm -rf "$FMV_DIR_BIN"; then
-        error "Failed to remove existing FVM directory: $FMV_DIR_BIN."
+# Check if BIN_DIR exists, and if it does delete it
+if [ -d "$BIN_DIR_BIN" ]; then
+    log_message "BIN bin directory already exists. Removing it."
+    if ! rm -rf "$BIN_DIR_BIN"; then
+        error "Failed to remove existing $BIN_NAME directory: $BIN_DIR_BIN."
     fi
 fi
 
-# Download FVM
-URL="https://github.com/leoafarias/fvm/releases/download/$FVM_VERSION/fvm-$FVM_VERSION.tar.gz"
-if ! curl -L "$URL" -o fvm.tar.gz; then
+# Download BIN
+URL="$downloadUrl/$BIN_VERSION.tar.gz"
+if ! curl -L "$URL" -o $BIN_NAME.tar.gz; then
     error "Download failed. Check your internet connection and URL: $URL"
 fi
 
 
 # Extract binary to the new location
-if ! tar xzf fvm.tar.gz -C "$FVM_DIR" 2>&1; then
+if ! tar xzf $BIN_NAME.tar.gz -C "$BIN_DIR" 2>&1; then
     error "Extraction failed. Check permissions and tar.gz file integrity."
 fi
 
 # Cleanup
-if ! rm -f fvm.tar.gz; then
+if ! rm -f $BIN_NAME.tar.gz; then
     error "Failed to cleanup"
 fi
 
-# Rename FVM_DIR/fvm to FVM_DIR/bin
-if ! mv "$FVM_DIR/fvm" "$FMV_DIR_BIN"; then
-    error "Failed to move fvm to bin directory."
+mkdir -p "$BIN_DIR_BIN" || error "Failed to create bin directory: $BIN_DIR_BIN."
+# Rename
+if ! mv "$BIN_DIR/$projectName-$BIN_VERSION/$BIN_NAME" "$BIN_DIR_BIN/"; then
+    error "Failed to move $BIN_NAME to bin directory."
 fi
 
 # Create a symlink
-if ! ln -sf "$FMV_DIR_BIN/fvm" "$SYMLINK_TARGET"; then
+if ! ln -sf "$BIN_DIR_BIN/$BIN_NAME" "$SYMLINK_TARGET"; then
     error "Failed to create symlink."
 fi
 
 # Verify installation
-if ! command -v fvm &> /dev/null; then
-    error "Installation verification failed. FVM may not be in PATH or failed to execute."
+if ! command -v $BIN_NAME &> /dev/null; then
+    error "Installation verification failed. $BIN_NAME may not be in PATH or failed to execute."
 fi
 
-INSTALLED_VERSION=$(fvm --version 2>&1) || error "Failed to verify installed FVM version."
-success "FVM $INSTALLED_VERSION installed successfully."
+# Cleanup
+if ! rm -rf $BIN_DIR/$projectName-$BIN_VERSION; then
+    error "Failed to cleanup $BIN_DIR/$projectName-$BIN_VERSION"
+fi
+
+INSTALLED_VERSION=$($BIN_NAME --version 2>&1) || error "Failed to verify installed $BIN_NAME version."
+success "$BIN_NAME $INSTALLED_VERSION installed successfully."
+
